In [5]:
#Lets import necessory libreries

import cv2
import numpy as np

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [6]:
#Read the image nad convert into a grayscale

image=cv2.imread(r"C:\Users\TAR-TT060-Saurav K\Desktop\Untitled.png")
image=cv2.resize(image,None,fx=0.9,fy=0.9)

In [7]:

#Lets convert in gray

gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

In [10]:
cv2.imshow("Gray Scaler",gray)

cv2.waitKey(12000)

cv2.destroyAllWindows()

In [12]:
#Now convert the grayscale image to binary image

ret,binary=cv2.threshold(gray,0,255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)

In the above code we converted the gray scale into binary. using THRESH_OTSU

In [14]:
#Now detect the contours 

contours , hierarchy = cv2.findContours(binary,mode=cv2.RETR_TREE,method=cv2.CHAIN_APPROX_NONE)

In [15]:
print(hierarchy)

[[[-1 -1  1 -1]
  [ 3 -1  2  0]
  [-1 -1 -1  1]
  [ 6  1  4  0]
  [-1 -1  5  3]
  [-1 -1 -1  4]
  [-1  3  7  0]
  [-1 -1  8  6]
  [-1 -1  9  7]
  [-1 -1 10  8]
  [-1 -1 11  9]
  [-1 -1 12 10]
  [-1 -1 13 11]
  [-1 -1 -1 12]]]


In [17]:
#Visualize the data structure 
print("Length of Contours{}",format(len(contours)))
print(contours)

Length of Contours{} 14
(array([[[0, 0]],

       [[0, 1]],

       [[0, 2]],

       ...,

       [[3, 0]],

       [[2, 0]],

       [[1, 0]]], dtype=int32), array([[[167,  91]],

       [[168,  90]],

       [[169,  90]],

       ...,

       [[164,  92]],

       [[165,  92]],

       [[166,  91]]], dtype=int32), array([[[129, 166]],

       [[129, 167]],

       [[129, 168]],

       [[129, 169]],

       [[128, 170]],

       [[128, 171]],

       [[128, 172]],

       [[128, 173]],

       [[128, 174]],

       [[128, 175]],

       [[128, 176]],

       [[128, 177]],

       [[127, 178]],

       [[127, 179]],

       [[127, 180]],

       [[127, 181]],

       [[126, 182]],

       [[126, 183]],

       [[126, 184]],

       [[126, 185]],

       [[126, 186]],

       [[125, 187]],

       [[125, 188]],

       [[125, 189]],

       [[125, 190]],

       [[125, 191]],

       [[124, 192]],

       [[124, 193]],

       [[124, 194]],

       [[124, 195]],

       [[123, 196]],


In [18]:
#Draw contours on th object image

image_copy=image.copy()
image_copy=cv2.drawContours(image_copy,contours,-1,(0,255,0),thickness=2)
image_copy

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [24]:
#Visualizing the results
cv2.imshow('Gray Scale Image',gray)
cv2.imshow('Drawn Contours',image_copy)
cv2.imshow('Binary Image',binary)

cv2.waitKey(20000)
cv2.destroyAllWindows()

In [23]:
#Employee of Tardid Technoloies
#Data Scientist - Saurav

#Date -> 15:10

#Time -> 5-07-2023